### PR TITLE
add Header pattern to view options

### PR DESCRIPTION
**Pull request by francescobragagna**
Hi,

I would like to use this library, but a graphic limitation was into the text of GanttDatePoint where chinese text was hardcoded.
e.g. into day.ts  yyyy年MM月 for  2022年01月 
I've added a HeaderPattern where you can write multiple different date formatting. 
see for example what I wrote into gantt.compoent.ts 
new GanttHeaderTemplate('{0} {1} (week {2})', ['LLLL', 'yyyy', 'w'])  when used with .apply(aGanttDate) will be written as   
January 2022 (week 1)

### CODE REVIEW

**Comment by walkerkay** [comment]
> Hi,
> 
> I would like to use this library, but a graphic limitation was into the text of GanttDatePoint where chinese text was hardcoded. e.g. into day.ts yyyy年MM月 for 2022年01月 I've added a HeaderPattern where you can write multiple different date formatting. see for example what I wrote into gantt.compoent.ts new GanttHeaderTemplate('{0} {1} (week {2})', ['LLLL', 'yyyy', 'w']) when used with .apply(aGanttDate) will be written as January 2022 (week 1)

I'm very glad you can submit PR for ngx-gantt. internationalizable is being supported and is expected to be released in the next version.

**Comment by francescobragagna** [comment]
Hi walkerkay,

I will submit another PR for hours view (i wrote the code few days ago, but it's not completed).
Can you please write me an email, to have a direct contact? my name is Francesco Bragagna, my business email is bragagna@esteco.com

Thank you

**Comment by walkerkay** [comment]
> Hi walkerkay,
> 
> I will submit another PR for hours view (i wrote the code few days ago, but it's not completed). Can you please write me an email, to have a direct contact? my name is Francesco Bragagna, my business email is [bragagna@esteco.com](mailto:bragagna@esteco.com)
> 
> Thank you

I've sent you an email

**Comment by HandsomeButterball** [comment]
> Hi,
> 
> I would like to use this library, but a graphic limitation was into the text of GanttDatePoint where chinese text was hardcoded. e.g. into day.ts yyyy年MM月 for 2022年01月 I've added a HeaderPattern where you can write multiple different date formatting. see for example what I wrote into gantt.compoent.ts new GanttHeaderTemplate('{0} {1} (week {2})', ['LLLL', 'yyyy', 'w']) when used with .apply(aGanttDate) will be written as January 2022 (week 1)

Hi,

We support this by injecting global configuration, you can pull the code. Examples are as follows:

```javascript
import { GANTT_GLOBAL_CONFIG } from 'ngx-gantt';

@Component({
    selector: 'app-gantt-example',
    templateUrl: './gantt.component.html',
    providers: [
        {
            provide: GANTT_GLOBAL_CONFIG,
            useValue: {
                dateFormat: {
                    ...
                }
            }
        }
    ]
})

```
 You can also use `viewOptions` parameter like this:

```html
<ngx-gantt [viewOptions]="viewOptions"> ... </ngx-gantt>
```

```javascript
@Component({
  selector: 'app-gantt-example',
  templateUrl: './gantt.component.html'
})
export class AppGanttExampleComponent {
  viewOptions: GanttViewOptions = {
    dateFormat: {
      yearQuarter: `QQQ 'of' yyyy`,
      month: 'LLLL',
      yearMonth: `LLLL yyyy'(week' w ')'`
    }
  };

  constructor() {}
}
```
Hope these can help you.

**Pull request closed without merging**
